#!/usr/bin/env bash
set -euo pipefail

HERE="$(dirname "$(readlink -f "$0")")"

export PATH="$HERE/usr/bin:$PATH"

if [[ -d "$HERE/usr/lib" ]]; then
    export LD_LIBRARY_PATH="$HERE/usr/lib:${LD_LIBRARY_PATH:-}"
fi

exec "$HERE/usr/bin/reshadelinux-gui.sh" "$@"